# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12E7qpooYrr65Dy9Wl90tNd2bxXLotX11

#This project covers following skills:

* Being able to use numpy and pandas to preprocess a dataset.

* Being able to use numpy to build a machine learning pipeline for supervised learning. 

* Being able to follow the steps involved in an end-to-end project in machine learning.

* Being able to use scikit-learn to design a machine learning model pipeline

# A dataset of air quality

The dataset you will use in this assignment comes from a popular machine learning repository that hosts open source datasets for educational and research purposes, the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php). We are going to use regularised ridge regression and random forests for predicting air quality. The description of the dataset can be found [here](https://archive.ics.uci.edu/ml/datasets/Air+Quality).
"""

import urllib.request
doq = "https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip"
pat_sav = "./AirQualityUCI.zip"
urllib.request.urlretrieve(doq, pat_sav)
#urllib.request.urlretrieve("https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip")

import zipfile
zip = zipfile.ZipFile('./AirQualityUCI.zip', 'r')
for name in zip.namelist():
    zip.extract(name, '.')

# The .csv version of the file has some typing issues, so we use the excel version
import pandas as pd 
air_quality_full = pd.read_excel('./AirQualityUCI.xlsx', usecols=range(2,15))

"""We can see some of the rows in the dataset """

air_quality_full.sample(5)

"""The target variable corresponds to the CO(GT) variable of the first column. The following columns correspond to the variables in the feature vectors, *e.g.*, PT08.S1(CO) is $x_1$ up until AH which is $x_D$. The original dataset also has a date and a time columns that we are not going to use in this assignment.

### Removing instances 

The dataset has missing values tagged with a -200 value. To simplify the design of the machine learning models in this assignment, we perform the following two operations to the dataset right from the beginning:

* we will remove the rows for which the target variable has missing values. We are doing supervised learning so we need all our data observations to have known target values.

* we will remove features with more than 20% of missing values. 

The code below performs both operations
"""

# We first remove the rows for which there are missing values in the target feature
air_quality = air_quality_full.loc[air_quality_full.iloc[:, 0]!=-200, :]

# We now remove the columns (features) for which there are more that 20% of missing values
import numpy as np
ndata, ncols = np.shape(air_quality) # number of data observations and number of columns in the dataframe
pmissing = np.empty(ncols)         # An empty vector that will keep the percentage of missing values per feature
for i in range(ncols):
    pmissing[i] = (air_quality.iloc[:, i]==-200).sum()/ndata # Computes the percentage of missing values per column
air_quality = air_quality.loc[:, pmissing < 0.2]

"""### Splitting the dataset 

Before designing any machine learning model, we need to set aside the test data. We will use the remaining training data for fitting the model. *It is important to remember that the test data has to be set aside before preprocessing*. 

Any preprocessing that you do has to be done only on the training data and several key statistics need to be saved for the test stage.  Separating the dataset into training and test before any preprocessing has happened help us to recreate the real world scenario where we will deploy our system and for which the data will come without any preprocessing.

Furthermore, we are going to use *hold-out validation* for validating our predictive model so we need to further separate the training data into a training set and a validation set.

We split the dataset into a training set, a validation set and a test set. The training set will have 70% of the total observations, the validation set 15% and the test set, the remaining 15%. For making the random selections of the training and validation sets **make sure that you use a random seed that corresponds to the last five digits of your student UCard**. In the code below, I have used 55555 as an example of my random seed.
"""

np.random.seed(70629)                 # Make sure you use the last five digits of your student UCard as your seed
index = np.random.permutation(ndata)  # We permute the indexes 
N = np.int64(np.round(0.70*ndata))    # We compute N, the number of training instances
Nval = np.int64(np.round(0.15*ndata)) # We compute Nval, the number of validation instances   
Ntest = ndata - N - Nval              # We compute Ntest, the number of test instances
data_training_unproc = air_quality.iloc[index[0:N], :].copy() # Select the training data
data_val_unproc = air_quality.iloc[index[N:N+Nval], :].copy() # Select the validation data
data_test_unproc = air_quality.iloc[index[N+Nval:ndata], :].copy() # Select the test data

"""The assigment is divided into two sections. In the **first section**, you will design a regularised ridge regression model trained with stochastic gradient descent. You will write all the code from scratch. You should not use any library that already implements any of the routines considered in this section, for example, scikit-learn. In the **second section**, you will design a random forests model and you are allowed to use scikit-learn in this section.

When writing your code, you will find out that there are operations that are repeated at least twice. We will assign marks for use of Python functions and for commenting your code. The marks will be assigned as:

* Did you include Python functions to solve the question and avoid repeating code? (**1 mark**)
* Did you comment your code to make it readable to others? (**1 mark**)

# 1. Using regularised ridge regression to predict air quality (10 marks)

**DO NOT USE scikit-learn or any other machine learning library for the questions on this section. You are meant to write Python code from scratch. You can use Pandas and Numpy. Using scikit-learn or any other machine learning library for the questions in this section will give ZERO marks. No excuse will be accepted.**

Regularisation is a technique commonly used in Machine Learning to prevent overfitting. It consists on adding terms to the objective function such that the optimisation procedure avoids solutions that just learn the training data. Popular techniques for regularisation in Supervised Learning include [Lasso Regression](https://en.wikipedia.org/wiki/Lasso_(statistics)), [Ridge Regression](https://en.wikipedia.org/wiki/Tikhonov_regularization) and the [Elastic Net](https://en.wikipedia.org/wiki/Elastic_net_regularization). 

In this part of the Assignment, you will be looking at Ridge Regression and implementing equations to optimise the objective function using the update rules for stochastic gradient descent. You will use those update rules for making predictions on the Air Quality dataset.

## 1.1 Ridge Regression

Let us start with a data set for training $\mathcal{D} = \{\mathbf{y}, \mathbf{X}\}$, where the vector $\mathbf{y}=[y_1, \cdots, y_N]^{\top}$ and $\mathbf{X}$ is the design matrix from Lab 4, this is, 

\begin{align*}
    \mathbf{X} = 
                \begin{bmatrix}
                        1 & x_{1,1} & \cdots & x_{1, D}\\
                        1 & x_{2,1} & \cdots & x_{2, D}\\
                   \vdots &  \vdots\\
                        1 & x_{N,1} & \cdots & x_{N, D}
                \end{bmatrix}
               = 
               \begin{bmatrix}
                      \mathbf{x}_1^{\top}\\
                       \mathbf{x}_2^{\top}\\
                          \vdots\\
                        \mathbf{x}_N^{\top}
                \end{bmatrix}.
\end{align*}

Our predictive model is going to be a linear model

$$ f(\mathbf{x}_i) = \mathbf{w}^{\top}\mathbf{x}_i,$$

where $\mathbf{w} = [w_0\; w_1\; \cdots \; w_D]^{\top}$.

The **objective function** we are going to use has the following form

$$ E(\mathbf{w}, \lambda) = \frac{1}{N}\sum_{n=1}^N (y_n - f(\mathbf{x}_n))^2 + \frac{\lambda}{2}\sum_{j=0}^D w_j^2,$$

where $\lambda>0$ is known as the *regularisation* parameter.

This objective function was studied in Lecture 4. 

The first term on the rhs is what we call the "fitting" term whereas the second term in the expression is the regularisation term. Given $\lambda$, the two terms in the expression have different purposes. The first term is looking for a value of $\mathbf{w}$ that leads the squared-errors to zero. While doing this, $\mathbf{w}$ can take any value and lead to a solution that it is only good for the training data but perhaps not for the test data. The second term is regularising the behavior of the first term by driving the $\mathbf{w}$ towards zero. By doing this, it restricts the possible set of values that $\mathbf{w}$ might take according to the first term. The value that we use for $\lambda$ will allow a compromise between a value of $\mathbf{w}$ that exactly fits the data (first term) or a value of $\mathbf{w}$ that does not grow too much (second term).

This type of regularisation has different names: ridge regression, Tikhonov regularisation or $\ell_2$ norm regularisation. 

## 1.2 Optimising the objective function with respect to $\mathbf{w}$

There are two ways we can optimise the objective function with respect to $\mathbf{w}$. The first one leads to a closed form expression for $\mathbf{w}$ and the second one using an iterative optimisation procedure that updates the value of $\mathbf{w}$ at each iteration by using the gradient of the objective function with respect to $\mathbf{w}$,
$$
\mathbf{w}_{\text{new}} = \mathbf{w}_{\text{old}} - \eta \frac{d E(\mathbf{w}, \lambda)}{d\mathbf{w}},
$$
where $\eta$ is the *learning rate* parameter and $\frac{d E(\mathbf{w}, \lambda)}{d\mathbf{w}}$ is the gradient of the objective function.

It can be shown (this is a question in the Exercise Sheet 4) that a closed-form expression for the optimal $\mathbf{w}_*$ is given as

\begin{align*}            
            \mathbf{w}_*& = \left(\mathbf{X}^{\top}\mathbf{X} + \frac{\lambda N}   
                                     {2}\mathbf{I}\right)^{-1}\mathbf{X}^{\top}\mathbf{y}.
\end{align*}

Alternatively, we can find an update equation for $\mathbf{w}_{\text{new}}$ using gradient descent leading to:

\begin{align*}
   \mathbf{w}_{\text{new}} & = \mathbf{w}_{\text{old}} - \eta \frac{d E(\mathbf{w}, \lambda)}
                              {d\mathbf{w}},\\
                           & = \mathbf{w}_{\text{old}} +  \frac{2\eta}{N}\sum_{n=1}^N   
                               \left(y_n - \mathbf{x}_n^{\top}\mathbf{w}_{\text{old}}\right)\mathbf{x}_n  
                       - \eta\lambda\mathbf{w}_{\text{old}}\\
                           & = (1 - \eta\lambda)\mathbf{w}_{\text{old}} + \frac{2\eta}
                               {N}\sum_{n=1}^N   
                               \left(y_n - \mathbf{x}_n^{\top}\mathbf{w}_{\text{old}}\right)\mathbf{x}_n
\end{align*}

## 1.3 Preprocessing the data

As mentioned before, the dataset has missing values tagged with a -200 value. Before doing any work with the training data, we want to make sure that we deal properly with the missing values. Furthermore, once we have dealt with the missing values, we want to standardise the training data. 

### Question 1.a: Missing values and standardisation (2 marks)

* For all the other features with missing values, use the mean value of the non-missing values for that feature to perform imputation. Save these mean values, you will need them when performing the validation stage (**1 mark**).

* Once you have imputed the missing data, we need to standardise the input vectors. Standardise the training data by substracting the mean value for each feature and dividing the result by the standard deviation of each feature. Keep the mean values and standard deviations, you will need them at validation time (**1 mark**).

#### Question 1.a Answer
"""

#In this task the following datasets wil be used:
#data_training_unproc - Select the training data
#data_val_unproc - Select the val data
#data_test_unproc - Select the test data

#Functions below are created for the first and second point of the Question 1.a
#Missing values(-200) replacement with mean
def replace_miss(dataset, mean_set=None):
  column_means = {}
  try:
    if mean_set!= None:
      column_means = mean_set
    for column in dataset.columns:
      #temp_col is a temporary array of all the elements from the selected columns exclduing the -200 value
      if mean_set!= None:
        dataset[column] = [value if value != -200 else mean_set[column] for value in dataset[column]]
      else:
        temp_col = [i for i in dataset[column] if i != -200]
        mean_col = np.mean(temp_col)
        column_means[column] = mean_col
      #final -200 values replacement
        dataset[column] = [value if value != -200 else mean_col for value in dataset[column]]
    return column_means
  except:
    return "sorry, error occured during this replacement"

#Additional separate function for mean calculation
def mean_calc(single_column):
  meancol = np.mean(single_column)
  return meancol


def standarization(dataset, mean_set=None, std_set=None):
    column_std = {}
    try:
      if std_set != None:
        column_std = std_set
      for column in dataset.columns:
        #standarizatin function is also prepared for handling datasets not 
        #being preprocessed with replace_miss function earlier
        if mean_set != None:
          mean_col = mean_set[column]
        else:
          temp_col = [i for i in dataset[column] if i != -200]
          mean_col = np.mean(temp_col)
        if std_set != None:
          stand_dev = std_set[column]
        else:
          stand_dev = np.std(dataset[column])
          column_std[column] = stand_dev
        dataset[column] = [(value - mean_col) / stand_dev for value in dataset[column]]
      return column_std
    except:
      return "sorry, error occured during this standarization"

#for better data analysis and understanding the dataframe of the training set is displayed below
data_training_unproc.iloc[:20]

#First and second point - (missing values + standarization) preprocessing the training data
training_set = data_training_unproc.copy()

#the variable miss_vals stores means for all the columns
miss_vals = replace_miss(training_set)

#the variable standard_vals stores standard deviations for all the columns
standard_vals = standarization(training_set, mean_set=miss_vals)

#as we can see missing values are replaced and standarization is applied
training_set.iloc[:20]

"""## 1.4 Training and validation stages

We have now curated our training data by removing data observations and features with a large amount of missing values. We have also normalised the feature vectors. We are now in a good position to work on developing the prediction model and validating it. We will use gradient descent for iterative optimisation. 

We first organise the dataframe into the vector of targets $\mathbf{y}$, call it `yTrain`, and the design matrix $\mathbf{X}$, call it `XTrain`.
"""

# Answer 1.4 - Spliting the preprocessed training set to features and target value
yTrain = training_set.iloc[:,0]
xTrain = training_set.iloc[:,1:]

#target variable CO(GT) is removed from xTrain
xTrain

#target variable CO(GT) - yTrain
yTrain

"""### Question 1.b: finding the optimal $\mathbf{w}$ with stochastic gradient descent (3 marks)

Use gradient descent to iteratively compute the value of $\mathbf{w}_{\text{new}}$. Instead of using all the training set in `XTrain` and `yTrain` to compute the gradient, use a subset of $S$ instances in `XTrain` and `yTrain`. This is sometimes called *minibatch gradient descent* where $S$ is the size of the minibacth. When using gradient descent with minibatches, you need to find the best values for three parameters: $\eta$, the learning rate, $S$, the number of datapoints in the minibatch and $\gamma$, the regularisation parameter.

* In this question we will use the validation data. So before proceeding to the next steps, make sure that you:  replace the missing values on each feature variables with the mean value you computed with the training data; standardise the validation data using the means and standard deviations computed from the training data (**1 mark**).
    
* Create a grid of values for the parameters $\gamma$ and $\eta$ using `np.logspace` and a grid of values for $S$ using `np.linspace`. Because you need to find three parameters, start with five values for each parameter in the grid and see if you can increase it. Make sure you understand what is the meaning of `np.logspace` and `np.linspace`. Notice that you can use negative values for `start` in `np.logspace` (**1 mark**).

* For each value that you have of $\gamma$, $\eta$ and $S$ from the previous step, use the training set to compute $\mathbf{w}$ using minibatch gradient descent and then measure the RMSE over the validation data. For the validation data, make sure you preprocess it before applying the prediction model over it. For the minibatch gradient descent choose to stop the iterative procedure after $200$ iterations (**1 mark**).

* Choose the values of $\gamma$, $\eta$ and $S$ that lead to the lowest RMSE and save them. You will use them at the test stage.

#### Question 1.b Answer
"""

#displaying the unprocessed validation set to analyze the data
data_val_unproc.iloc[:20]

#First bulletpoint - replacing missing values in validation set and standarization
validation_set = data_val_unproc.copy()
miss_validation = replace_miss(validation_set, mean_set=miss_vals)
standard_validation = standarization(validation_set, mean_set=miss_vals, std_set=standard_vals)

validation_set.iloc[:20]

#second point - grid creation for the regularization parameter, batch size and learning rate(5 values for each parameter)
#in case of the minibatch size value needs to be an integer as it represents the number of datapoints
size_grid = np.linspace(5, 100, 5, dtype=int)
learning_rate_grid = np.logspace(-6,-2,5)
regularization_parameter_grid = np.logspace(-4,1,5)

#creating parameters dataframe
parameters = [size_grid, learning_rate_grid, regularization_parameter_grid]
parameters = np.array(parameters).T

#displaying the parameters values
grid_parameters = pd.DataFrame(parameters, columns=["minibatch size", "learning rate", "regularization parameter"])
grid_parameters

#Spliting the validation set
yVal = validation_set.iloc[:,0]
xVal = validation_set.iloc[:,1:]

#third point - For each value that you have of  γ ,  η  and  S  from the previous step, use the training set to compute  w  using minibatch gradient descent and then measure the RMSE over the validation data.
# For the validation data, make sure you preprocess it before applying the prediction model over it. 
#For the minibatch gradient descent choose to stop the iterative procedure after  200  iterations
import random

#seed based on my Ucard number
np.random.seed(70629)
random.seed(70629)

#Best RMSE and parameter values initialization
min_rmse = np.inf
min_batch_size = np.inf
min_eta = np.inf
min_gamma = np.inf

#number of epochs
num_epochs = 200

#initialization of the parameters list
rmse_parameter = []


def gradient_calculation(xSet, ySet, weights, regularization=0, lr=0.001, batch_size=10):
  r = random.sample(range(xSet.shape[0]), batch_size)
  xBatch = xSet.iloc[r]
  yBatch = ((ySet.iloc[r]).values).reshape(-1,1)

  gradient = (-np.dot(xBatch.T, yBatch) + np.dot(np.dot(xBatch.T,xBatch),weights)) + np.dot(regularization,weights)
  weights = weights - lr * gradient
  return weights

def RMSE_calculation(xValSet, yValSet, weights):
  valWeights = (np.dot(xValSet, weights))
  diff_mse = np.squeeze(np.asarray((yValSet.values).reshape(-1,1) - valWeights))
  mse = ((1/len(xValSet))*np.dot(diff_mse, diff_mse.T))
  return np.sqrt(mse)

#minibatch gradient descent
for gamma in regularization_parameter_grid:   
    for eta in learning_rate_grid:        
        for batch_size in size_grid:    

            #random weights initialization
            weights = 0.5*np.random.randn(11,1)
            for i in range(num_epochs):
                weights = gradient_calculation(xSet = xTrain,ySet = yTrain, regularization = gamma, lr = eta, batch_size = batch_size, weights= weights)

            rmse = RMSE_calculation(xVal, yVal, weights)
            
            rmse_parameter.append([gamma, eta, batch_size, rmse])
            if rmse < min_rmse:
                min_rmse = rmse
                min_batch_size = batch_size
                min_eta = eta
                min_gamma = gamma
            print('Parameters: α: {}, η: {}, β: {}, result in RMSE: {}'.format(gamma, eta, batch_size, rmse))

print('Lowest RMSE recorded:', min_rmse)

#forth point answer - choosing the parameters resulting in the lowest RMSE
rmse_parameter_frame = pd.DataFrame(rmse_parameter,columns=["regularization", "learning rate", "batch size", "RMSE"])
rmse_parameter_frame

#forth point answer
print('best batch size: ', min_batch_size)
print('best learning rate: ', min_eta)
print('best L2 regularization: ', min_gamma)
print('minimum RMSE: ', min_rmse)

"""## 1.5 Test stage 

We now know which one is the best model, according to the validation data. We will now put together the training data and the validation data, perform the preprocessing as we did before, this is, treat the missing values and standardise the inputs. We will train the model again using the minibatch stochastic gradient descent and finally compute the RMSE over the test data.


### Question 1.c: combine the original training and original validation data and perform the preprocessing again to this new data (2 marks)

Put together the original training and validation dataset and perform the same preprocessing steps than before, these are: 

* for each feature, impute the missing values with the mean values of the non-missing values (**1 mark**) 

* stardardise the new training set (**1 mark**).

#### Question 1.c Answer
"""

# first point join unprocesssed training and validation sets and process them

#my preprocessing methods require keeping the same names of the columns, threfore pd.concat was used instead of np.vstack 
new_training_set = [data_training_unproc.copy(), data_val_unproc.copy()]
new_training_set = pd.concat(new_training_set)

#first point - impute missing values with mean
miss_new_train = replace_miss(new_training_set)

#second point - standarization
standard_new_train = standarization(new_training_set, mean_set=miss_new_train)

# new training set displayed for analysis and proof it is preprocessed
new_training_set[:20]

"""### Question 1.d: Preprocess the test data, train the model and predict over the test data (3 marks)

Preprocess the test data and train a new model using the new training set. Finally, report the RMSE over the test set:

* Preprocess the test data by imputing the missing data and standardising it (**1 mark**). 

* Use the best values of $\gamma$, $\eta$ and $S$ found in the validation set and train a new regularised linear model with stochastic gradient descent (**1 mark**).

* Report the RMSE over the test data (**1 mark**).

#### Question 1.d Answer
"""

# first point - missing data removal and standarization
test_set = data_test_unproc.copy()
miss_test = replace_miss(test_set, mean_set=miss_new_train)
standard_test = standarization(test_set, mean_set=miss_new_train, std_set=standard_new_train)

# test set displayed for analysis and proof it is preprocessed
test_set[:20]

#before moving to the second point both new train and test sets need to be splitted

yNewtrain = new_training_set.iloc[:,0]
xNewtrain = new_training_set.iloc[:,1:]

yTest = test_set.iloc[:,0]
xTest = test_set.iloc[:,1:]

#second bulletpoint - Use the best values of  γ ,  η  and  S  found in the validation set and train a new regularised linear model with stochastic gradient descent

#basic initialization
np.random.seed(70629)
num_epochs = 200
new_weights = 0.5*np.random.randn(11,1)
#parameters are taken from the min variables previous task(min_eta, min_gamma, min_batch_size)

for i in range(num_epochs):
    new_weights = gradient_calculation(xSet = xNewtrain,ySet = yNewtrain, regularization = min_gamma, lr = min_eta, batch_size = min_batch_size, weights= new_weights)

rmse = RMSE_calculation(xTest, yTest, new_weights)


#third point -  RMSE on the test set
print('The RMSE on the test set is: {}'.format( rmse))

"""# 2. Random forests (13 marks)

**USE scikit-learn for the questions on this section.**

In section 1, you used a regularised ridge regression model trained with SGD to create a linear predictive model. In this part of the assignment, you will use **scikit-learn** to train a random forest for regression over the air quality dataset.

## 2.1 Preprocessing the data

As mentioned before, the dataset has missing values tagged with a -200 value. Before doing any work with the training data, we want to make sure that we deal properly with the missing values. Furthermore, once we have dealt with the missing values, we want to standardise the training data. 

### Question 2.a: Pipeline for missing values and standardisation (3 marks)

* Employ the `SimpleImputer` method in Scikit-learn to impute the missing values in each column using the mean value of the non-missing values, instead (**1 mark**).

* Standardise the data by substracting the mean value for each feature and dividing the result by the standard deviation of each feature. Employ the `StandardScaler` method (**1 mark**).

* Create a `Pipeline` that you can use to preprocess the data by filling missing values and then standardising the features (**1 mark**).

#### Question 2.a Answer
"""

##new initialized sets for the Question 2 
training_setQ2 = data_training_unproc.copy()
validation_setQ2 = data_val_unproc.copy()
test_setQ2 = data_test_unproc.copy()

#displaying and checking the training set for Q2 
training_setQ2.iloc[:20]

#first point Simple Imputer on training set
from sklearn.impute import SimpleImputer

Q2_imputer = SimpleImputer(missing_values=-200, strategy='mean')
Q2_imputer.fit(training_setQ2)
training_setQ2 = Q2_imputer.transform(training_setQ2)

#Second point - Standard Scaler on the training set
from sklearn.preprocessing import StandardScaler

Q2_scaler = StandardScaler()
Q2_scaler.fit(training_setQ2)
training_setQ2 = Q2_scaler.transform(training_setQ2)

#training set display after preprocessing
pd.DataFrame(training_setQ2[:20])

#third point - Pipeline creation including the simple imputer and standard scaler
from sklearn.pipeline import Pipeline
pipelineQ2 = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean', missing_values=-200)),
    ('scaler', StandardScaler())
])

"""### Question 2.b: Use the Pipeline to fit the training data and transform the validation data (2 marks)

In the previous question, you created a `Pipeline` for applying a `SimpleImputer` and a `StandardScaler`. Use the Pipeline to fit the training data (**1 mark**) and transform the validation data (**1 mark**).

#### Question 2.b Answer
"""

#display the validation set before applying the preprocessing pipeline
validation_setQ2.iloc[:20]

#ANSWER to 2.b
training_setQ2_pipe = data_training_unproc.copy()
pipelineQ2.fit(training_setQ2_pipe)
validation_setQ2 = pipelineQ2.transform(validation_setQ2)

#validation set display after preprocessing
pd.DataFrame(validation_setQ2[:20])

"""## 2.2 Random forest to predict air quality 

We now use random forests to predict air quality. Remember that the tree ensemble in random forests is built by training individual regression trees on different subsets of the training data and using a subset of the available features. For regression, the prediction is the average of the individual predictions of each tree. Some of the parameters required in the Random Forest implementation in Scikit-learn include:

Some of the additional parameters required in the Random Forest implementation in Scikit-learn include

> **n_estimators** the total number of trees to train<p>
**max_features** number of features to use as candidates for splitting at each tree node. <p>
    **boostrap**: Whether bootstrap samples are used when building trees. If False, the whole dataset is used to build each tree.<p>
   **max_samples**: If bootstrap is True, the number of samples to draw from X to train each base estimator.

### Question 2.c: train a random forest (4 marks)

In this question, you will train a random forest for predicting over the validation data. Use cross-validation over the validation data to select the best set of paramaters for the random forest regressor. Parameters to include in your exploration are **n_estimators**, **max_features** and **max_samples**. Use `np.linspace` or `np.logspace` to define ranges of values to explore for each parameter and create a grid to be assessed over the validation data. Make sure you use the same validation data that was given to you.

* Use `PredefinedSplit` to tell the cross validator which instances to use for training and which ones for validation (**1 mark**).

* Create a grid of values to explore that include a range of at least five values for each parameter **n_estimators**, **max_features** and **max_samples** (**1 mark**). 

* Train a random forest for regression model that uses the grid of parameters you created before. Use `GridSearchCV` to find the best set of parameters by performing cross-validation over the predefined split. (**1 mark**).

* Print the best values in your grid for **n_estimators**, **max_features** and **max_samples** (**1 mark**).

#### Question 2.c Answer
"""

#joining training and validation sets
new_training_setQ2 = np.vstack((training_setQ2, validation_setQ2))
new_training_setQ2.shape

#first point - predefinedSplit - Use PredefinedSplit to tell the cross validator which instances to use for training and which ones for validation
from sklearn.model_selection import PredefinedSplit
test_fold = np.zeros((np.shape(new_training_setQ2)[0], 1))
test_fold[0:np.shape(data_training_unproc)[0]] = 1
ps = PredefinedSplit(test_fold)
print(ps)

# second point - Create a grid of values to explore that include a range of at least five values for each parameter n_estimators, max_features and max_samples

n_estimators_grid = np.linspace(10,400, 5, dtype=int)
max_features_grid = np.linspace(2,11,5, dtype=int)
max_samples_grid = np.linspace(5, 300, 5, dtype=int)

#creating random forest parameters dataframe
forest_parameters = [n_estimators_grid, max_features_grid, max_samples_grid]
forest_parameters = np.array(forest_parameters).T

#displaying the forest parameters values
grid_forest_parameters = pd.DataFrame(forest_parameters, columns=["n_estimators_grid", "max_features_grid", "max_samples_grid"])
grid_forest_parameters

yNewTrainSetQ2 = new_training_setQ2[:,0]
xNewTrainSetQ2 = new_training_setQ2[:,1:]

pd.DataFrame(xNewTrainSetQ2)

# third point - Train a random forest for regression model that uses the grid of parameters you created before. Use GridSearchCV to find the best set of parameters by performing cross-validation over the predefined split. 
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

forest_parameters_grid = dict(n_estimators = n_estimators_grid, max_samples = max_samples_grid, max_features = max_features_grid)
grid_regression_Question3 = GridSearchCV(RandomForestRegressor(), param_grid=forest_parameters_grid, cv=ps, scoring='neg_mean_squared_error')
grid_regression_Question3.fit(xNewTrainSetQ2, yNewTrainSetQ2)

# fourth point - Print the best values in your grid for n_estimators, max_features and max_samples

print('Best number of estimators: ', grid_regression_Question3.best_params_["n_estimators"])
print('Best number of samples: ', grid_regression_Question3.best_params_["max_samples"])
print('Best number of features: ', grid_regression_Question3.best_params_["max_features"])

"""### Question 2.d: train a new model over the whole training data and report the prediction over the test set (4 marks)


Now that we have identified the best paramaters of the regression model, we use these parameters to train a new model over the whole training data (`data_training` plus `data_val`). We apply this model to the test set and report the performance.

* Create a new preprocessing pipeline for taking care of the missing values and standardisation over the whole training data (**1 mark**).

* Apply the created preprocessing pipeline to the test data (**1 mark**).

* Fit a random forest regression model to the training data using the best parameters found in Question 2.c (**1 mark**).

* Compute the RMSE over the test data and report the result (**1 mark**).

#### Question 2.d Answer
"""

# first point - Create a new preprocessing pipeline for taking care of the missing values and standardisation over the whole training data
##new initialized sets for the Question 2.d
training_setQ2 = data_training_unproc.copy()
validation_setQ2 = data_val_unproc.copy()
test_setQ2 = data_test_unproc.copy()

whole_training_setQ2 = np.vstack((training_setQ2, validation_setQ2))

#the pipelineQ2 will be reused for this task
pipelineQ2.fit(whole_training_setQ2)
whole_training_setQ2 = pipelineQ2.transform(whole_training_setQ2)

#second point - pipeline application on the test set
test_setQ2 = pipelineQ2.transform(test_setQ2)

pd.DataFrame(test_setQ2)

ywhole_training_setQ2 = whole_training_setQ2[:,0]
xwhole_training_setQ2 = whole_training_setQ2[:,1:]

ytest_setQ2 = test_setQ2[:,0]
xtest_setQ2 = test_setQ2[:,1:]

#third point - Fit a random forest regression model to the training data using the best parameters found in Question 2.c

## Training a Random Forest using the best value for the  n_estimators and max_samples
RandFor_Q2 = RandomForestRegressor(n_estimators=grid_regression_Question3.best_params_["n_estimators"],max_samples=grid_regression_Question3.best_params_["max_samples"], max_features=grid_regression_Question3.best_params_["max_features"])
RandFor_Q2.fit(xwhole_training_setQ2, ywhole_training_setQ2)
RandFor_Q2_pred = RandFor_Q2.predict(xtest_setQ2)

##fourth point - Compute the RMSE over the test data and report the result 
## import of the sklearn mean_squared_error function
from sklearn.metrics import mean_squared_error

RMSE_RandForQ2 = np.sqrt(mean_squared_error(ytest_setQ2, RandFor_Q2_pred))
print('The RMSE on the test data is :',RMSE_RandForQ2)